# Generated by Django 3.1.2 on 2020-10-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='akart/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='subcatagory',
            field=models.CharField(default='', max_length=50),
        ),
    ]
