# Generated by Django 3.1.2 on 2020-10-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akart', '0002_auto_20201025_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
