# Generated by Django 3.1.2 on 2020-10-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akart', '0003_auto_20201029_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdetails',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=70)),
                ('contact_email', models.CharField(max_length=50)),
                ('contact_phone', models.BigIntegerField()),
                ('contact_feedback', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(max_length=500),
        ),
    ]
