# Generated by Django 3.1.2 on 2020-11-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akart', '0004_auto_20201029_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdetails',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('ordername', models.CharField(max_length=90)),
                ('orderaddress', models.CharField(max_length=150)),
                ('orderaddress1', models.CharField(max_length=150)),
                ('ordercontact', models.BigIntegerField()),
                ('ordercontact1', models.BigIntegerField()),
                ('ordercity', models.CharField(max_length=40)),
                ('orderstate', models.CharField(max_length=40)),
                ('orderpincode', models.BigIntegerField()),
                ('orderemail', models.CharField(max_length=70)),
                ('orderpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
