# Generated by Django 3.1.2 on 2021-03-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akart', '0006_ordertracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='orderamount',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
