# Generated by Django 3.1.2 on 2021-03-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akart', '0007_orderdetails_orderamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='orderamount',
            field=models.IntegerField(default=0),
        ),
    ]
