# Generated by Django 3.2.7 on 2021-09-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akart', '0008_auto_20210313_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='items_json',
            field=models.TextField(),
        ),
    ]
