# Generated by Django 3.2.7 on 2021-09-14 17:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akart', '0009_alter_orderdetails_items_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracker',
            name='order_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='akart.orderdetails'),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TXNID', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('TXNAMOUNT', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('PAYMENTMODE', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('CURRENCY', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('TXNDATE', models.DateTimeField(default=datetime.datetime.now)),
                ('STATUS', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('RESPCODE', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('RESPMSG', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('GATEWAYNAME', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('BANKTXNID', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('BANKNAME', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('order_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='akart.orderdetails')),
            ],
        ),
    ]
