# Generated by Django 3.2.7 on 2021-09-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akart', '0010_auto_20210914_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
