# Generated by Django 3.2.7 on 2021-09-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akart', '0011_alter_orderpayment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracker',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
